number: 1
part: 1
description: "Write a function <b>time_to_seconds(time)</b> which takes a <b>str</b> as a parameter and returns a time
in second as a <b>float</b>. The function should accept the following <b>str</b> format for the parameter <b>time</b>:
<ul>
  <li>
    <b>mm:ss.fff</b> where two digits are always used for minutes (m), seconds (s), and three digits for the fraction
    of a second (f). For example <b>02:05.512</b> represents 2 minutes and 5 seconds and 512 milliseconds. The returned
    value should be 125.512.
  </li>
  <li>
    <b>ss.fff</b> where two digits are always used for seconds (s) and  three digits for the fraction of a second (f).
    For example <b>01.250</b> represents a second and 250 milliseconds. This format is used when the time is less than
    an minute. The returned value should be 1.25.
  </li>
  <li>Any other format must raise a <b>ValueError</b> exception.</li>
  <li>
    The seconds (ss) must be strictly less than 60, otherwise a <b>ValueError</b> exception should be raised. For
    example <b>'01:62.500'</b> should raise an exception.
  </li>
</ul>"
max_mark: 12
part_name: Time Conversion
method_name: time_to_seconds
